{
 "title": "Defenders",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Defender cost time series",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  created AS \"time\",\n  cost\nFROM transfer, player\nWHERE\n  $__timeFilter(created)\nAND transfer.player_id = player.id\nAND player.role LIKE 'D'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Budget % spent for defenders",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  team.name AS \"Team\", SUM(transfer.cost)/500::float * 100 AS \"Budget (%)\"\nFROM roster, transfer, team, player\nWHERE roster.transfer_id = transfer.id\nAND roster.fantasy_team_id = team.id\nAND roster.player_id = player.id\nAND player.role LIKE 'D'\nGROUP BY team.name"
    }
   ]
  },
  {
   "title": "Defenders transfer list",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\n  created,\n  player.name,\n  player.team,\n  cost\nFROM transfer, player\nWHERE\n  $__timeFilter(created)\nAND transfer.player_id = player.id\nAND player.role LIKE 'D'\nORDER BY cost"
    }
   ]
  },
  {
   "title": "Defenders Free",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT\n  player.name,\n  player.team,\n  player.value\nFROM player\nLEFT OUTER JOIN transfer ON player.id = transfer.player_id\nWHERE player.role LIKE 'D'\nAND transfer.dest_fantasy_team_id IS NULL\nORDER BY player.value\n"
    }
   ]
  }
 ]
}