{
 "title": "Goalkeepers",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Cost time series",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  created_at AS \"time\",\n  cost\nFROM\n  auction_transfer,\n  auction_footballer\nWHERE\n  $__timeFilter(auction_transfer.created_at)\n  AND auction_transfer.footballer_id = auction_footballer.id\n  AND auction_footballer.role LIKE 'P'\nORDER BY\n  1"
    }
   ]
  },
  {
   "title": "Budget % spent",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  auction_team.name AS \"Team\", SUM(auction_transfer.cost)/500::float * 100 AS \"Budget (%)\", SUM(auction_transfer.cost) AS expense\nFROM auction_transfer, auction_team, auction_footballer\nWHERE auction_transfer.buyer_id = auction_team.id\nAND auction_footballer.id = auction_transfer.footballer_id\nAND auction_footballer.role LIKE 'G'\nGROUP BY auction_team.name"
    }
   ]
  },
  {
   "title": "Transfer list",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\n  auction_transfer.created_at,\n  auction_footballer.name,\n  auction_footballer.team,\n  auction_transfer.cost,\n  auction_footballer.fantasy_value\nFROM auction_transfer, auction_footballer\nWHERE\n  $__timeFilter(auction_transfer.created_at)\nAND auction_transfer.footballer_id = auction_footballer.id\nAND auction_footballer.role LIKE 'P'\nORDER BY cost"
    }
   ]
  },
  {
   "title": "Free players",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\n  auction_footballer.name,\n  auction_footballer.team,\n  auction_footballer.fantasy_value\nFROM auction_footballer\nLEFT OUTER JOIN auction_transfer ON auction_footballer.id = auction_transfer.footballer_id\nWHERE auction_footballer.role LIKE 'P'\nAND auction_transfer.buyer_id IS NULL\nORDER BY auction_footballer.value\n"
    }
   ]
  }
 ]
}