{
 "title": "Real Pollo",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Roster",
   "type": "table",
   "description": "Real Pollo roster",
   "gridPos": { "h": 15, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  player.role, player.name, player.team, transfer.cost\nFROM roster, transfer, team, player\nWHERE roster.transfer_id = transfer.id\nAND roster.fantasy_team_id = team.id\nAND roster.player_id = player.id\nAND team.name LIKE 'Real Pollo'\n"
    }
   ]
  },
  {
   "title": "Max estimated offer for DIFESA",
   "type": "table",
   "description": "Budget 90",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT name, 8 - COALESCE(num_players, 0) AS \"toBuy\", COALESCE(expense.bought,0) AS \"bought\", 90 - COALESCE(expense.tot,0) - (8 - COALESCE(num_players, 0)) + 1 AS tot_expense\n            FROM team\n            LEFT JOIN (\n                SELECT roster.fantasy_team_id AS id, COUNT(roster.fantasy_team_id) AS num_players\n                FROM roster\n                INNER JOIN player ON roster.player_id = player.id\n                WHERE player.role = 'D'\n                GROUP BY roster.fantasy_team_id) AS count\n\t\t\tON team.id = count.id\n\t\t\tLEFT JOIN (\n\t\t\t\tSELECT roster.fantasy_team_id, COALESCE(SUM(transfer.cost), 0) AS tot, COALESCE(COUNT(transfer.cost), 0) AS bought\n\t\t\t\tFROM roster\n\t\t\t\tINNER JOIN transfer ON roster.transfer_id = transfer.id\n\t\t\t\tWHERE roster.player_id IN (\n\t\t\t\t\tSELECT id FROM player\n\t\t\t\t\tWHERE role = 'D')\n\t\t\t\tGROUP BY roster.fantasy_team_id\n\t\t\t) AS expense\n\t\t\tON team.id = expense.fantasy_team_id\n\t\t\tORDER BY tot_expense DESC"
    }
   ]
  },
  {
   "title": "Max estimated offer for CENTROCAMPO",
   "type": "table",
   "description": "Budget 125",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT name, 8 - COALESCE(num_players, 0) AS \"toBuy\", COALESCE(expense.bought,0) AS \"bought\", 80 - COALESCE(expense.tot,0) - (8 - COALESCE(num_players, 0)) + 1 AS tot_expense\n            FROM team\n            LEFT JOIN (\n                SELECT roster.fantasy_team_id AS id, COUNT(roster.fantasy_team_id) AS num_players\n                FROM roster\n                INNER JOIN player ON roster.player_id = player.id\n                WHERE player.role = 'C'\n                GROUP BY roster.fantasy_team_id) AS count\n\t\t\tON team.id = count.id\n\t\t\tLEFT JOIN (\n\t\t\t\tSELECT roster.fantasy_team_id, COALESCE(SUM(transfer.cost), 0) AS tot, COALESCE(COUNT(transfer.cost), 0) AS bought\n\t\t\t\tFROM roster\n\t\t\t\tINNER JOIN transfer ON roster.transfer_id = transfer.id\n\t\t\t\tWHERE roster.player_id IN (\n\t\t\t\t\tSELECT id FROM player\n\t\t\t\t\tWHERE role = 'C')\n\t\t\t\tGROUP BY roster.fantasy_team_id\n\t\t\t) AS expense\n\t\t\tON team.id = expense.fantasy_team_id\n\t\t\tORDER BY tot_expense DESC"
    }
   ]
  },
  {
   "title": "Budget expense (%)",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT\n  player.role AS \"Role\", SUM(transfer.cost)/500::float * 100 AS \"Budget (%)\", SUM(transfer.cost)\nFROM roster, transfer, team, player\nWHERE roster.transfer_id = transfer.id\nAND roster.fantasy_team_id = team.id\nAND roster.player_id = player.id\nAND team.name LIKE 'Real Pollo'\nGROUP BY player.role\n"
    }
   ]
  },
  {
   "title": "Max estimated offer for ATTACCO",
   "type": "table",
   "description": "Budget 245",
   "gridPos": { "h": 7, "w": 8, "x": 6, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT name,\n\t6 - COALESCE(num_players, 0) AS \"toBuy\",\n\tCOALESCE(expense.bought,0) AS \"bought\",\n\t245 - COALESCE(expense.tot,0) - (6 - COALESCE(num_players, 0)) + 1 AS est_offer,\n\tCOALESCE(500 - team_expense.tot - (25-team_expense.bought) + 1, 500-25+1) AS max_offer\n            FROM team\n            LEFT JOIN (\n                SELECT roster.fantasy_team_id AS id, COUNT(roster.fantasy_team_id) AS num_players\n                FROM roster\n                INNER JOIN player ON roster.player_id = player.id\n                WHERE player.role = 'A'\n                GROUP BY roster.fantasy_team_id) AS count\n\t\t\tON team.id = count.id\n\t\t\tLEFT JOIN (\n\t\t\t\tSELECT roster.fantasy_team_id, COALESCE(SUM(transfer.cost), 0) AS tot, COALESCE(COUNT(transfer.cost), 0) AS bought\n\t\t\t\tFROM roster\n\t\t\t\tINNER JOIN transfer ON roster.transfer_id = transfer.id\n\t\t\t\tWHERE roster.player_id IN (\n\t\t\t\t\tSELECT id FROM player\n\t\t\t\t\tWHERE role = 'A')\n\t\t\t\tGROUP BY roster.fantasy_team_id\n\t\t\t) AS expense\n\t\t\tON team.id = expense.fantasy_team_id\n\t\t\tLEFT JOIN (\n\t\t\t\tSELECT roster.fantasy_team_id, COALESCE(SUM(transfer.cost), 0) AS tot, COALESCE(COUNT(transfer.cost), 0) AS bought\n\t\t\t\tFROM roster\n\t\t\t\tINNER JOIN transfer ON roster.transfer_id = transfer.id\n\t\t\t\tGROUP BY roster.fantasy_team_id\n\t\t\t) AS team_expense\n\t\t\tON team.id = team_expense.fantasy_team_id\n\t\t\tORDER BY est_offer DESC"
    }
   ]
  }
 ]
}