version: '3.1'

services:
  grafana:
    image: grafana/grafana:latest
    depends_on:
      - "postgres"
    ports:
      - 3000:3000
    volumes:
      - ./provisioning:/etc/grafana/provisioning

  postgres:
    build: .
    ports:
      - 5432:5432