version: '3.1'

services:
  grafana:
    image: grafana/grafana:latest
    depends_on:
      - "postgres"
    ports:
      - 3000:3000
    volumes:
      - ./provisioning:/etc/grafana/provisioning

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: fantacalcio
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data