# Generated by Django 4.2.2 on 2023-06-26 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Footballer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('role', models.CharField(choices=[('G', 'Goalkeeper'), ('D', 'Defender'), ('C', 'Midfielder'), ('F', 'Forward')], max_length=1)),
                ('team', models.CharField(max_length=200)),
                ('value', models.PositiveIntegerField()),
                ('fantasy_value', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('president', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer', to='auction.team')),
                ('footballer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auction.footballer')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller', to='auction.team')),
            ],
        ),
    ]
