# Generated by Django 4.2.2 on 2023-07-08 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='cost',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
