# Generated by Django 4.2.2 on 2023-07-08 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0002_transfer_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footballer',
            name='role',
            field=models.CharField(choices=[('P', 'Portiere'), ('D', 'Difensore'), ('C', 'Centrocampista'), ('A', 'Attaccante')], max_length=1),
        ),
    ]
