# Generated by Django 4.2.2 on 2023-07-08 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0003_alter_footballer_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seller', to='auction.team'),
        ),
    ]
