# Generated by Django 4.2.2 on 2023-07-08 09:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0004_alter_transfer_created_at_alter_transfer_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 8, 9, 52, 25, 327796)),
        ),
    ]
