# Generated by Django 4.2.2 on 2023-07-08 09:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0005_alter_transfer_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 8, 9, 53, 50, 512307, tzinfo=datetime.timezone.utc)),
        ),
    ]
