# Generated by Django 4.2.2 on 2023-07-08 09:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0007_alter_transfer_buyer_alter_transfer_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 8, 9, 58, 9, 63044, tzinfo=datetime.timezone.utc)),
        ),
    ]
