# Generated by Django 4.2.2 on 2023-07-08 10:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0013_team_credits_alter_transfer_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='footballer',
            name='external_id',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transfer',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 8, 10, 19, 43, 805267, tzinfo=datetime.timezone.utc)),
        ),
    ]
