# Generated by Django 4.2.2 on 2023-07-08 10:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0014_footballer_external_id_alter_transfer_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footballer',
            name='external_id',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 8, 10, 20, 17, 976881, tzinfo=datetime.timezone.utc)),
        ),
    ]
