# Generated by Django 4.2.2 on 2023-07-29 08:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0015_alter_footballer_external_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='credits',
        ),
        migrations.AlterField(
            model_name='transfer',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 29, 8, 5, 13, 660784, tzinfo=datetime.timezone.utc)),
        ),
    ]
