# Generated by Django 4.2.2 on 2023-07-29 08:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0016_remove_team_credits_alter_transfer_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='credits',
            field=models.PositiveIntegerField(default=500),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 29, 8, 45, 42, 951592, tzinfo=datetime.timezone.utc)),
        ),
    ]
