{
 "title": "Rosters",
 "time": { "from": "2022-08-05T10:00:00.000Z", "to": "2022-08-07T09:59:59.998Z" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Real Pollo",
   "type": "table",
   "gridPos": { "h": 11, "w": 4, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  player.name, role, player.team, cost\nFROM transfer, player\nWHERE $__timeFilter(created)\nAND transfer.player_id = player.id\nAND transfer.dest_fantasy_team_id = 1\nORDER BY created"
    }
   ]
  },
  {
   "title": "Pompy FC",
   "type": "table",
   "gridPos": { "h": 11, "w": 4, "x": 4, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  player.name, role, player.team, cost\nFROM transfer, player\nWHERE $__timeFilter(created)\nAND transfer.player_id = player.id\nAND transfer.dest_fantasy_team_id = 2\nORDER BY created"
    }
   ]
  },
  {
   "title": "Patetico Mineiro",
   "type": "table",
   "gridPos": { "h": 11, "w": 4, "x": 8, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  player.name, role, player.team, cost\nFROM transfer, player\nWHERE $__timeFilter(created)\nAND transfer.player_id = player.id\nAND transfer.dest_fantasy_team_id = 3\nORDER BY created"
    }
   ]
  },
  {
   "title": "Paris Saint Germano",
   "type": "table",
   "gridPos": { "h": 11, "w": 4, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  player.name, role, player.team, cost\nFROM transfer, player\nWHERE $__timeFilter(created)\nAND transfer.player_id = player.id\nAND transfer.dest_fantasy_team_id = 4\nORDER BY created"
    }
   ]
  },
  {
   "title": "Apoel Kan 1893",
   "type": "table",
   "gridPos": { "h": 11, "w": 4, "x": 16, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  player.name, role, player.team, cost\nFROM transfer, player\nWHERE $__timeFilter(created)\nAND transfer.player_id = player.id\nAND transfer.dest_fantasy_team_id = 5\nORDER BY created"
    }
   ]
  },
  {
   "title": "Ire Framba United",
   "type": "table",
   "gridPos": { "h": 11, "w": 4, "x": 0, "y": 11 },
   "targets": [
    {
     "rawSql": "SELECT\n  player.name, role, player.team, cost\nFROM transfer, player\nWHERE $__timeFilter(created)\nAND transfer.player_id = player.id\nAND transfer.dest_fantasy_team_id = 6\nORDER BY created"
    }
   ]
  },
  {
   "title": "Godopolisportiva Antonio Ricci",
   "type": "table",
   "gridPos": { "h": 11, "w": 4, "x": 4, "y": 11 },
   "targets": [
    {
     "rawSql": "SELECT\n  player.name, role, player.team, cost\nFROM transfer, player\nWHERE $__timeFilter(created)\nAND transfer.player_id = player.id\nAND transfer.dest_fantasy_team_id = 7\nORDER BY created"
    }
   ]
  },
  {
   "title": "MedusaTeam WFC",
   "type": "table",
   "gridPos": { "h": 11, "w": 4, "x": 8, "y": 11 },
   "targets": [
    {
     "rawSql": "SELECT\n  player.name, role, player.team, cost\nFROM transfer, player\nWHERE $__timeFilter(created)\nAND transfer.player_id = player.id\nAND transfer.dest_fantasy_team_id = 8\nORDER BY created"
    }
   ]
  },
  {
   "title": "Reggisenal",
   "type": "table",
   "gridPos": { "h": 11, "w": 4, "x": 12, "y": 11 },
   "targets": [
    {
     "rawSql": "SELECT\n  player.name, role, player.team, cost\nFROM transfer, player\nWHERE $__timeFilter(created)\nAND transfer.player_id = player.id\nAND transfer.dest_fantasy_team_id = 9\nORDER BY created"
    }
   ]
  },
  {
   "title": "Rolling Stoned",
   "type": "table",
   "gridPos": { "h": 11, "w": 4, "x": 16, "y": 11 },
   "targets": [
    {
     "rawSql": "SELECT\n  player.name, role, player.team, cost\nFROM transfer, player\nWHERE $__timeFilter(created)\nAND transfer.player_id = player.id\nAND transfer.dest_fantasy_team_id = 10\nORDER BY created"
    }
   ]
  }
 ]
}